### PR TITLE
DiskAddress is already a more efficient Option<>

### PR DESCRIPTION
**Pull request by rkuris**
This removes Option<DiskAddress> from BranchNodes

### CODE REVIEW

**Review by richardpringle — CHANGES_REQUESTED** [review]
Please no... I don't disagree with the change, but please not now lol

**Review by xinifinity — APPROVED** [review]
LGTM, although, talked to @richardpringle offline, it seems this conflicts with his major refactor/work on Merkle with https://github.com/ava-labs/firewood/pull/344. Not sure how easy or does it make sense to rebase on top?

**Review by richardpringle — CHANGES_REQUESTED** [review]
Upon further review, I don't think that we should do this. It doesn't make sense to have an uninitialized `DiskAddress`. The only valid place that I see this happening is related to `Extension` nodes and currently, calling `serialize` on a `DiskAddress` that has not been initialized will panic. 

Instead, `DiskAddress` should simply wrap `NonZeroUsize`, and parent types can use `Option<DiskAddress>`.

**Comment by rkuris** [comment]
Lets change DiskAddress to not be an Option.

**Pull request closed without merging**
