### PR TITLE
Proposals are immutable

### PR DESCRIPTION
**Pull request by rkuris**
We shouldn't keep the StoreRevMut around in the Proposal, especially now since you can't iterate on a mutable revision.

### CODE REVIEW

**Review by richardpringle — APPROVED** [review]

**Comment by richardpringle** [comment]
It's really weird that there's a test failure from the minimal changes here...

**Review by xinifinity — APPROVED** [review]
A quick glance doesn't occur to me why such small changes could cause the test failure.

**Comment by rkuris** [comment]
This fails because [StoreRevShared's write method is stubbed out](https://github.com/ava-labs/firewood/blob/main/firewood/src/storage/mod.rs#L353).

Why does this ever get called if we're flushing everything? This appears to happen when allocating space. The stack for this is:
```
   2: <firewood::storage::StoreRevShared as firewood::shale::CachedStore>::write
             at ./src/storage/mod.rs:355:9
   3: firewood::shale::Obj<T>::flush_dirty
             at ./src/shale/mod.rs:156:13
   4: <firewood::shale::Obj<T> as core::ops::drop::Drop>::drop
             at ./src/shale/mod.rs:174:9
   5: core::ptr::drop_in_place<firewood::shale::Obj<firewood::shale::compact::CompactFooter>>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
   6: firewood::shale::compact::CompactSpaceInner<M>::alloc_new
             at ./src/shale/compact.rs:530:5
   7: firewood::shale::compact::CompactSpaceInner<M>::alloc::{{closure}}
             at ./src/shale/compact.rs:537:17
   8: core::result::Result<T,E>::and_then
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1316:22
   9: firewood::shale::compact::CompactSpaceInner<M>::alloc
             at ./src/shale/compact.rs:533:9
  10: <firewood::shale::compact::CompactSpace<T,M> as firewood::shale::ShaleStore<T>>::put_item
             at ./src/shale/compact.rs:589:20
  11: firewood::merkle::Merkle<S,T>::init_root
             at ./src/merkle.rs:177:9
  12: firewood::db::Db::new_revision::{{closure}}::{{closure}}
             at ./src/db.rs:811:37
  13: firewood::db::Db::new_revision::{{closure}}
             at ./src/db.rs:810:27
  14: firewood::shale::Obj<T>::write
             at ./src/shale/mod.rs:122:9
  15: firewood::db::Db::new_revision
             at ./src/db.rs:808:13
  16: firewood::db::Db::new_internal
             at ./src/db.rs:626:29
  17: firewood::db::Db::new::{{closure}}::{{closure}}
             at ./src/db.rs:496:27
```

**Comment by rkuris** [comment]
Closed due to design changes

**Pull request closed without merging**
