### PR TITLE
update clap dependency

### PR DESCRIPTION
**Pull request by danlaine**

### CODE REVIEW

**Comment by rkuris** [comment]
I am checking to see why clap didn't auto-update from dependabot, so please hold off on updating this. Do you need these features for your other PR?

**Comment by rkuris** [comment]
Ah, clap 4.5 is 2 hours old. Is your build failing because it says it's out of date?

**Review by richardpringle — APPROVED** [review]

**Comment by danlaine** [comment]
> Ah, clap 4.5 is 2 hours old. Is your build failing because it says it's out of date?

Yeah linting is failing on this other PR due to this old dependency https://github.com/ava-labs/firewood/actions/runs/7833600540/job/21375035516?pr=476#step:10:1

**Comment by rkuris** [comment]
> Yeah linting is failing on this other PR due to this old dependency https://github.com/ava-labs/firewood/actions/runs/7833600540/job/21375035516?pr=476#step:10:1

OK so the version upgrade check is no longer blocking. This can be merged when ready. I don't know why dependabot missed this one.

**Review by rkuris — APPROVED** [review]

**Pull request merged**
