### PR TITLE
Move proof to be a sub-module of merkle

### PR DESCRIPTION
**Pull request by richardpringle**
Proofs only make sense in the context of a merkle-tree, therefore they should be a submodule of the merkle module.

### CODE REVIEW

**Review by rkuris — CHANGES_REQUESTED** [review]
The API returns proofs, so we want api::Proof to be visible to callers. Otherwise, the whole merkle module has to be pub.

**Comment by richardpringle** [comment]
> The API returns proofs, so we want api::Proof to be visible to callers. Otherwise, the whole merkle module has to be pub.

I thought the `api` module was just a mechanism for serving two apis at the same time. We shouldn't have a separate module for the public API, there's a reason that no one does this. 

>Otherwise, the whole merkle module has to be pub.

This specifically is incorrect. The whole purpose of `pub use merkle::Proof` (called in the `db.rs`) solves this problem. The `Proof` type and the `impl Proof` should live in the same place.

**Review by xinifinity — APPROVED** [review]

**Comment by rkuris** [comment]
> > The API returns proofs, so we want api::Proof to be visible to callers. Otherwise, the whole merkle module has to be pub.
> 
> I thought the `api` module was just a mechanism for serving two apis at the same time. We shouldn't have a separate module for the public API, there's a reason that no one does this.
> 
> > Otherwise, the whole merkle module has to be pub.
> 
> This specifically is incorrect. The whole purpose of `pub use merkle::Proof` (called in the `db.rs`) solves this problem. The `Proof` type and the `impl Proof` should live in the same place.

This only works if `merkle::Proof` is also pub, which is what I want to avoid. This does not compile:

```
pub use inner::Thing;

mod inner {
    struct Thing {}
}
```

**Comment by richardpringle** [comment]
> > > The API returns proofs, so we want api::Proof to be visible to callers. Otherwise, the whole merkle module has to be pub.
> > 
> > 
> > I thought the `api` module was just a mechanism for serving two apis at the same time. We shouldn't have a separate module for the public API, there's a reason that no one does this.
> > > Otherwise, the whole merkle module has to be pub.
> > 
> > 
> > This specifically is incorrect. The whole purpose of `pub use merkle::Proof` (called in the `db.rs`) solves this problem. The `Proof` type and the `impl Proof` should live in the same place.
> 
> This only works if `merkle::Proof` is also pub, which is what I want to avoid. This does not compile:
> 
> ```
> pub use inner::Thing;
> 
> mod inner {
>     struct Thing {}
> }
> ```

but this does
https://github.com/ava-labs/firewood/pull/378/files#diff-648f516579918c7c3dddf3fd5eec6807c064b1ae8f8411d2c029bd804f7ef871R4

**Review by rkuris — APPROVED** [review]

**Pull request merged**
