### PR TITLE
Nibbles nits

### PR DESCRIPTION
**Pull request by gubatron**

### CODE REVIEW

**Review by rkuris — APPROVED** [review]
Thanks for fixing the typos and adding the `nth` method!

**Comment by rkuris** [comment]
@gubatron can you please sign the other commit and resubmit?

**Review by richardpringle — APPROVED** [review]

**Comment by richardpringle** [comment]
Hey @gubatron! 

Checkout [this StackOverflow article](https://stackoverflow.com/questions/41882919/is-there-a-way-to-gpg-sign-all-previous-commits) to see how to resign old commits!

**Comment by gubatron** [comment]
oops, only signed the last one. Fixing.

**Comment by gubatron** [comment]
Done, I think one more commit there got co-signed by me because the main branch was merged into this one (weird)

**Review by xinifinity — APPROVED** [review]

**Pull request merged**
